#!/usr/bin/env bash

# Link dotfiles
ln -s $(pwd)/.zshrc $HOME/.zshrc
ln -s $(pwd)/.p10k.zsh $HOME/.p10k.zsh
ln -s $(pwd)/.taskrc $HOME/.taskrc


# Install Oh my zsh
export KEEP_ZSHRC=yes
export RUNZSH=no
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install zsh navigation tools
sh -c "$(curl -fsSL https://raw.githubusercontent.com/psprint/zsh-navigation-tools/master/doc/install.sh)"

# Install p10k theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
cp -r powerlevel10k ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/
cp -r powerlevel10k/* ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/
rm -rf powerlevel10k

# Install fonts
git clone https://github.com/romkatv/powerlevel10k-media/
mkdir -p ~/.local/share/fonts
cp powerlevel10k-media/*.ttf ~/.local/share/fonts
rm -rf powerlevel10k-media


# Syntax highlight
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/opt/zsh-syntax-highlighting


# Set zsh default shell (requires password)
chsh -s $(which zsh)

# cp plugins/git.plugin.zsh  ~/.oh-my-zsh/plugins/git/git.plugin.zsh
