#!/usr/bin/env bash

[ -d ${HOME}/.config/nvim ] && mv ${HOME}/.config/nvim ${HOME}/.config/nvim.old
ln -s $(pwd)/nvimrc.d ${HOME}/.config/nvim


mkdir -p ~/.local/share/nvim/site/pack/packer/start/


export PYTHONPATH=${HOME}/opt/miniconda3/lib/python3.8/site-packages/
NVIM_RUNNING_FIRST_TIME_SETUP=true nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# mkdir -p $HOME/.config/coc
# ln -s $(pwd)/vim/.vimrc $HOME/.vimrc
# ln -s $(pwd)/vim/.vim $HOME/.vim

# curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# vim +PlugInstall +qall
# vim -c 'CocInstall -sync coc-python coc-snippets coc-clangd coc-texlab coc-json coc-html|qall'

# vim -c 'CocInstall -sync https://github.com/SvenBecker/vscode-pytorch|qall'

# pip show neovim || pip install neovim

# mkdir -p ${HOME}/.config/nvim
# ln -s $(pwd)/vim/init.vim ${HOME}/.config/nvim/init.vim
